#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  project: IrisLib.csproj
  
before_build: 
  - ps: nuget restore IrisLib.csproj -PackagesDirectory .\packages
  
artifacts:
  - path: .\bin\Release\IrisLib.dll
  - path: .\bin\Release\IrisLib.pdb
  - path: .\bin\Release\IrisLib.xml
  
deploy:
  release: IrisLib-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: h35HOYAmD8a2JAykXLvuYNT+hbv0AzCRFECJuaUZn8t8wf2u7fsmP3VILAdIrdpN # your encrypted token from GitHub
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
