#---------------------------------#
#       build configuration       #
#---------------------------------#

version: 1.0.{build}

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release
branches: 
  only:
    - master

clone_folder: c:\projects\threelib

assembly_info: 
  patch: true 
  file: AssemblyInfo.* 
  assembly_version: "{version}" 
  assembly_file_version: "{version}" 
  assembly_informational_version: "{version}"

build:
  project: .\src\ThreeLib.csproj
  
before_build: 
  - ps: nuget restore .\src\ThreeLib.csproj -PackagesDirectory .\packages
    
after_build:
  - ps: nuget pack .\src\ThreeLib.csproj -Version $env:appveyor_build_version
  - '%APPVEYOR_BUILD_FOLDER%\src\docgen\MarkdownGenerator.exe %APPVEYOR_BUILD_FOLDER%\src\bin\%CONFIGURATION%\ThreeLib.dll %APPVEYOR_BUILD_FOLDER%\src\docgen\docs'

environment:
  access_token:
    secure: fN1gPfV1hJKK/Xe2NqW/YG9xr/QXzURGC60C35jdhPE2vzv++Hg12sGgVjvDL/V7
  email:
    secure: TLIb25uvIfWDSHxTCa98IgkTG+JyVHdr0w6YKQDH4fU=
  name:
    secure: 4Tmu63pG75CB2ftIrSaD4w==
  version: "%APPVEYOR_BUILD_VERSION%"

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "$env:email"
  - git config --global user.name "$env:name"
  - git reset --hard origin/master
  - ps: >-
      If(!(Test-Path docs)){
        new-item -Name docs -ItemType directory
        cd docs
      } Else {
        cd docs
      }
  - git clone https://github.com/McNeel/threelib.wiki.git
  - ps: cd threelib.wiki
  - git rm *.md
  - git commit -m "delete docs"
  - git push -u origin master
  - ps: >-
      dir -r  | % { if ($_.PsIsContainer) { $_.FullName + "\" } else { $_.FullName } }
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/fraguada/threelib/artifacts/src/docgen/docs/Home.md'
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/fraguada/threelib/artifacts/src/docgen/docs/THREE.Cameras.md'
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/fraguada/threelib/artifacts/src/docgen/docs/THREE.Core.md'
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/fraguada/threelib/artifacts/src/docgen/docs/THREE.Geometries.md'
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/fraguada/threelib/artifacts/src/docgen/docs/THREE.Lights.md'
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/fraguada/threelib/artifacts/src/docgen/docs/THREE.Materials.md'
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/fraguada/threelib/artifacts/src/docgen/docs/THREE.Math.md'
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/fraguada/threelib/artifacts/src/docgen/docs/THREE.Objects.md'
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/fraguada/threelib/artifacts/src/docgen/docs/THREE.Textures.md'
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/fraguada/threelib/artifacts/src/docgen/docs/THREE.Utility.md'
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/fraguada/threelib/artifacts/src/docgen/docs/THREE.md'
  - ps: Rename-Item -Path "Home.md" -NewName "_Sidebar.md"
  - ps: New-Item "Home.md" -type file -value "Welcome to the ThreeLib Wiki. Navigate the API Reference with the sidebar ->"
  - git add *.md
  - ps: git commit -m "$env:version"
  - git clean -f
  - git push origin master -f

#on_success:
#  - echo Hello on Success
  
artifacts:
  - path: .\src\bin\Release\ThreeLib.dll
  - path: .\src\bin\Release\ThreeLib.pdb
  - path: .\src\bin\Release\ThreeLib.xml
  - path: .\src\docgen\docs\*
    name: docs
  - path: '*.nupkg'
    name: nugetpackage
  
#deploy:
#  - provider: NuGet
#    api_key:
#      secure: 7VFQFZaH5AKQsOF9Vsjq19s97afV+/9kq4SAyCoyJP5KnT3gro3f9Vqh2txUB4+X
#    artifact: nugetpackage
#  - provider: GitHub
#    auth_token:
#      secure: fN1gPfV1hJKK/Xe2NqW/YG9xr/QXzURGC60C35jdhPE2vzv++Hg12sGgVjvDL/V7
#    artifact: docs

