#---------------------------------#
#       build configuration       #
#---------------------------------#

version: 1.0.{build}

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release
branches: 
  only:
    - master

clone_folder: c:\projects\threelib

assembly_info: 
  patch: true 
  file: AssemblyInfo.* 
  assembly_version: "{version}" 
  assembly_file_version: "{version}" 
  assembly_informational_version: "{version}"

build:
  project: .\src\ThreeLib.csproj
  
before_build: 
  - ps: nuget restore .\src\ThreeLib.csproj -PackagesDirectory .\packages
    
after_build:
  - ps: nuget pack .\src\ThreeLib.csproj -Version $env:appveyor_build_version
  - '%APPVEYOR_BUILD_FOLDER%\src\docgen\MarkdownGenerator.exe %APPVEYOR_BUILD_FOLDER%\src\bin\%CONFIGURATION%\ThreeLib.dll %APPVEYOR_BUILD_FOLDER%\src\docgen\docs'
  
artifacts:
  - path: .\src\bin\Release\ThreeLib.dll
  - path: .\src\bin\Release\ThreeLib.pdb
  - path: .\src\bin\Release\ThreeLib.xml
  - path: .\src\docgen\docs\*.md
  - path: .\src\docgen\docs\
    name: docs
  - path: '*.nupkg'
    name: nugetpackage
  
deploy:
  provider: NuGet
  api_key:
    secure: 7VFQFZaH5AKQsOF9Vsjq19s97afV+/9kq4SAyCoyJP5KnT3gro3f9Vqh2txUB4+X
  artifact: nugetpackage

