#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  project: IrisLib.csproj
  
before_build: 
  - ps: nuget restore IrisLib.csproj -PackagesDirectory .\packages
  
after_build:
  - ps: nuget pack IrisLib.csproj
  
artifacts:
  - path: .\bin\Release\IrisLib.dll
  - path: .\bin\Release\IrisLib.pdb
  - path: .\bin\Release\IrisLib.xml
  - path: .\IrisLib.1.0.0.nupkg
  
deploy:
  provider: NuGet
  api_key:
    secure: EmdGz6NxrKEE9y1YFxLyYxhb4S31f1Bjq1lVSg6a4X37O6eb3QoA5kG0++XT1X/q
  artifact: /.*\.nupkg/

