#---------------------------------#
#       build configuration       #
#---------------------------------#

version: 1.0.{build}

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release
branches: 
  only:
    - master

clone_folder: c:\projects\threelib

assembly_info: 
  patch: true 
  file: AssemblyInfo.* 
  assembly_version: "{version}" 
  assembly_file_version: "{version}" 
  assembly_informational_version: "{version}"

build:
  project: ThreeLib.csproj
  
before_build: 
  - ps: nuget restore ThreeLib.csproj -PackagesDirectory .\packages
    
after_build:
  - ps: nuget pack ThreeLib.csproj -Version $env:appveyor_build_version
  
artifacts:
  - path: .\bin\Release\ThreeLib.dll
  - path: .\bin\Release\ThreeLib.pdb
  - path: .\bin\Release\ThreeLib.xml
  - path: '*.nupkg'
    name: nugetpackage
  
deploy:
  provider: NuGet
  api_key:
    secure: EmdGz6NxrKEE9y1YFxLyYxhb4S31f1Bjq1lVSg6a4X37O6eb3QoA5kG0++XT1X/q
  artifact: nugetpackage

