#---------------------------------#
#       build configuration       #
#---------------------------------#

version: 1.0.{build}

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release
branches: 
  only:
    - master

clone_folder: c:\projects\threelib

assembly_info: 
  patch: true 
  file: AssemblyInfo.* 
  assembly_version: "{version}" 
  assembly_file_version: "{version}" 
  assembly_informational_version: "{version}"

build:
  project: .\src\ThreeLib.csproj
  
before_build: 
  - ps: nuget restore .\src\ThreeLib.csproj -PackagesDirectory .\packages
    
after_build:
  - ps: nuget pack .\src\ThreeLib.csproj -Version $env:appveyor_build_version
  - '%APPVEYOR_BUILD_FOLDER%\src\docgen\MarkdownGenerator.exe %APPVEYOR_BUILD_FOLDER%\src\bin\%CONFIGURATION%\ThreeLib.dll %APPVEYOR_BUILD_FOLDER%\src\docgen\docs'

environment:
  access_token:
    secure: fN1gPfV1hJKK/Xe2NqW/YG9xr/QXzURGC60C35jdhPE2vzv++Hg12sGgVjvDL/V7
  email:
    secure: TLIb25uvIfWDSHxTCa98IgkTG+JyVHdr0w6YKQDH4fU=
  name:
    secure: 4Tmu63pG75CB2ftIrSaD4w==

after_deploy:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "$env:email"
  - git config --global user.name "$env:name"
  - git reset --hard origin/master
  - git checkout gh-pages
  - ps: cd docs
  - ps: Start-FileDownload 'https://github.com/mcneel/ThreeLib/blob/master/src/docgen/docs/Home.md'
  - git commit "docs commit"
  - git push origin gh-pages

on_success:
  - echo Hello on Success
  
artifacts:
  - path: .\src\bin\Release\ThreeLib.dll
  - path: .\src\bin\Release\ThreeLib.pdb
  - path: .\src\bin\Release\ThreeLib.xml
  - path: .\src\docgen\docs\*
    name: docs
  - path: '*.nupkg'
    name: nugetpackage
  
deploy:
  - provider: NuGet
    api_key:
      secure: 7VFQFZaH5AKQsOF9Vsjq19s97afV+/9kq4SAyCoyJP5KnT3gro3f9Vqh2txUB4+X
    artifact: nugetpackage
  - provider: GitHub
    auth_token:
      secure: fN1gPfV1hJKK/Xe2NqW/YG9xr/QXzURGC60C35jdhPE2vzv++Hg12sGgVjvDL/V7
    artifact: docs

